### ISSUE TITLE
unable to train url

### ISSUE THREAD

**Issue by ruili-pml** [VICO-UoE/URL#14]
Hi,

When I was trying to train the Universal Feature Extractor I had this error:

```
Traceback (most recent call last):
  File "/scratch/work/lir3/FSC/URL/train_net_url.py", line 109, in <module>
    sample = train_loader.get_train_batch(session)
  File "/scratch/work/lir3/FSC/URL/data/meta_dataset_reader.py", line 313, in get_train_batch
    return self._get_batch(self.train_dataset_next_task, session)
  File "/scratch/work/lir3/FSC/URL/data/meta_dataset_reader.py", line 296, in _get_batch
    episode = session.run(next_task)[0]
  File "/scratch/work/lir3/.conda_envs/ml/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 967, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/scratch/work/lir3/.conda_envs/ml/lib/python3.9/site-packages/tensorflow/python/client/session.py", line 1117, in _run
    raise RuntimeError('The Session graph is empty. Add operations to the '
RuntimeError: The Session graph is empty. Add operations to the graph before calling run().
```

Do you know how to fix it? Thank you

**Comment by ruili-pml** [comment]
running `./scripts/test_resnet18_pa.sh` has the same error

**Comment by hummarow** [comment]
Hi, @ruili-pml.
I was experencing the same issue,
and it was simply resolved by adding
`tf.compat.v1.disable_eager_execution()`
at the top, right after importing the module.

Hope this helps.
